### ISSUE TITLE
Walkthrough - Segment

### ISSUE THREAD

**Issue by HugoSchtr** [alix-tz/escriptorium-documentation#10]
This issue has been created for keeping track of the writing of the __Segment__ section.

- [x] Overwiew
- [x] Editing lines
- [x] Editing regions
- [x] Reordering

**Comment by alix-tz** [comment]
Feel free to use features brought by pymdownx.keys when you describe the shortcuts! I've added a little here: https://github.com/alix-tz/escriptorium-tutorial/wiki/Markdown-in-Mkdocs#keys

You can even use it to say that, for example, using the `++right-button++` is possible to move around in a zoomed-in image.

**Comment by alix-tz** [comment]
Hello! 

Just a reminder to not hesitate to use the section dedicated to segmentation in the current English tutorial (see: 1.4. Manually annotate documents in https://lectaurep.hypotheses.org/documentation/escriptorium-tutorial-en)

Also, not to hesitate to point to Kraken's documentation on segmentation: 
- https://kraken.re/master/advanced.html#page-segmentation
- https://kraken.re/master/advanced.html#baseline-segmentation
- https://kraken.re/master/advanced.html#principal-text-direction

**Comment by alix-tz** [comment]
I suggest we leave this issue open even if we already have a first version ready thanks to @FloChiff since we had a lot of ambitions to make it smoother!
