### ISSUE TITLE
Add illustration to "import models"

### ISSUE THREAD

**Issue by alix-tz** [alix-tz/escriptorium-documentation#24]
... in walkthrough_import.md

A GIF could illustrate steps to upload the model. 

- [ ] Make the demo GIF
- [ ] Add it to the subsection

--- 

A remaining issue after #17

**Comment by HugoSchtr** [comment]
The gif has been done since! :) 

https://escriptorium.readthedocs.io/en/latest/import/#import-models

I'm closing this issue! 👍
