### ISSUE TITLE
Add a shortcuts section?

### ISSUE THREAD

**Issue by HugoSchtr** [alix-tz/escriptorium-documentation#49]
I was thinking it could be useful to add a page where we would centralize all useful shortcuts, in addition to the ones we document in the different walkthroughs. 

I think it could be useful for people that just want to get a quick handle on the app and not go through every walkthrough. 

What do you think? :thinking:

**Comment by HugoSchtr** [comment]
Like for example, ctrl + backspace when you want to fit the image to the panel, etc.

**Comment by FloChiff** [comment]
I think that it is a good idea to centralize it all, because some people (*hum hum* me for example) know how to use eScriptorium but don't really know or forget the shortcuts, so it could be interesting to have a specific page for that.

**Comment by alix-tz** [comment]
Yes, we can add a page for all the known shortcuts, but we still need to have them listed here and there in the walk-through since it might be too much all at once ;)

Following a discussion with Floriane this morning, we should add elements of documentation when the shortcut is different on an apple keyboard.

**Comment by alix-tz** [comment]
Note that we can have this section in the page dedicated to tips in general.

**Comment by HugoSchtr** [comment]
Yes I agree with everything! @FloChiff I'll let you handle the apple keyboard shortcuts if that's okay!

**Comment by HugoSchtr** [comment]
Nice!

Could we make a list here of all the useful shortcuts we use?

**Comment by alix-tz** [comment]
I think it's a very good idea to start working on this section! 

Are there any shortcuts outside of the "edition" panel? (I can't think of any right now)

**Comment by HugoSchtr** [comment]
- Images tab shortcuts: the usual `alt` and `ctrl` select. Useful for selecting the images you want to segment/transcribe/export
- Edit tab: `ctrl` + `backspace` for fitting the image the image to the panel. Useful when you want to reset the view or if you messed up zooming.
- Edit tab: `ctrl` + `1/2/3/4/5` for opening panels.
- Segmentation panel: all shortcuts already listed in the manual segmentation walkthrough.
- Transcription panel: `enter` or `down` for saving the transcription and go to the next line ; `up` to go back to the previous line. Same for the text panel.
- Annotation: `backspace` for deleting an annotation.

**Comment by HugoSchtr** [comment]
@alix-tz, yes, I can think of the `shift` and `ctrl` selection for the images tab. :)

**Comment by FloChiff** [comment]
I just checked on my computer: all the shortcuts you mentioned are the same on the Mac, except for the shortcuts to select images, that need only to press `shift` (it does not work while also pressing `ctrl`)
Another shortcut that I don't think you mentioned : on Mac, once in 'Edit', you can press `ctrl` + `shift` and then click on the right or left arrow to navigate from one image to the other.

**Comment by HugoSchtr** [comment]
For selecting the images, I meant `shift` for selecting multiple images, and `ctrl` for selecting single image :)

**Comment by FloChiff** [comment]
I have a quick question for the segmentation shortcuts.
It appeared that way on my browser: is that normal ?
![shortcuts_segment](https://user-images.githubusercontent.com/45393720/236458287-ec3ed8d8-c0ba-4f5c-b6d1-c0dd0d3b6619.png)

**Comment by alix-tz** [comment]
No, they should appear like this: 

![image](https://user-images.githubusercontent.com/33317799/236464770-527a19c0-f93e-457e-b4ce-ccb808c38be7.png)

This needs to be fixed

**Comment by alix-tz** [comment]
To complete the list made by @HugoSchtr, we should also include when the Ctrl + A and Ctrl + Z can be used, don't you think?

And we could mention the notion of key binding as it is implemented in the virtual keyboard, which allows you to set sort of shortcuts for typing special characters

**Comment by alix-tz** [comment]
We could put the shortcuts section in terminology? or in the FAQ if we don't want to create a whole new page.

**Comment by FloChiff** [comment]
Fixed this with #85
