### ISSUE TITLE
Should the url in readthedocs be "escriptorium.rtd" in stead of "escriptorium-tutorial.rtd"?

### ISSUE THREAD

**Issue by alix-tz** [alix-tz/escriptorium-documentation#65]
After all, this is more than an tutorial...

**Comment by FloChiff** [comment]
I agree, especially since there is the whole "readthedocs" thing at the end, so just putting "escriptorium" is enough I think

**Comment by alix-tz** [comment]
Keeping track of a list of things remaining to do:
- [x] change repo description
- [x] change metadata and website description in the docs
- [ ] change logo
- [ ] change repo name/URL 
- [ ] set RTD to track the new URL

**Comment by FloChiff** [comment]
Why “change logo” in the checklist ? Do you not like it any more ? Does it have a problem ?

**Comment by alix-tz** [comment]
Yes, the logo contains the following text "eScriptorium Tutorial", it just needs to be changed to "eScriptorium Documentation", nothing major ;)

**Comment by alix-tz** [comment]
Hop! I think all the changes were made to switch to "documentation"!
