### ISSUE TITLE
Changing the order in nav?

### ISSUE THREAD

**Issue by alix-tz** [alix-tz/escriptorium-documentation#68]
In #67, @FloChiff  said:

> If we don't do alphabetically order and stay with what we have right now, I think I would put “Export data” below “Import data” and I would also bring “Train models” before all the “manual” stuff and then put “Search” after the “Virtual keyboard”.

**Comment by alix-tz** [comment]
When I was preparing #67 , since I moved Annotation after segmentation and transcription (because it's somewhat disconnected from the two), I wondered in "import data" should be followed by "export data". 

My reasoning against it was the following: since nav is walking us through that workflow of using eScriptorium, it made more sense to have export after the manual annotations (you import data, modifying them and then export the result). 

Another reason was that in export, we talk about transcription versions, zones, etc, which are not covered yet if we put export after import: they are elements covered in automatic prediction and manual segmentation/transcription.

On the other hand, training, searching (especially since it's not available on all platform) and virtual keyboard are not features that everybody needs to read about before they can use the platform, which are the reason for putting them after.

**Comment by HugoSchtr** [comment]
Mmh not necessarily, import data, export data, segment, training, etc. are all key features of eScriptorium, people will go look for those sections before everything else. User-related features are more common!

**Comment by FloChiff** [comment]
This issue is closed as we decide to leave the nav as it is
