### ISSUE TITLE
Precision needed for the 'draw annotation' part

### ISSUE THREAD

**Issue by FloChiff** [alix-tz/escriptorium-documentation#78]
I just tried the drawing of an annotation part on a document using the tutorial, and it was harder than I though because I didn't exactly know how to draw the annotation.
In the case of an annotation in the form of a rectangle, it is pretty easy because you only need to click once on your mouse from the top left corner of your rectangle and then go to the bottom right corner of it and then stop clicking in order to have your rectangle.
With the polygon, I struggle to find how to release the polygon once it is done (I apparently simply needed to double-click on my mouse to do it).
I think it might be useful to explain clearly on the walkthrough how we can draw each annotation.

**Comment by alix-tz** [comment]
Well, that fixes an issue I had: I still hadn't found a way to release drawing a polygon! 

I just tried it and I can confirm that double clicking works! And I agree that we should add it in the documentation :)

Thank you!

**Comment by FloChiff** [comment]
Ahah !!! Happy to help !!! 
I honestly tried so many things (Press `enter`, `backspace`, `space`, `ctrl`, etc.) and the double-clicking was only a stroke of luck.
Do you want me to do the modification and then a pull request for it ?

**Comment by alix-tz** [comment]
yes, feel free to do the PR!
